---
name: chauvenity-os
description: Personal image

base-image: ghcr.io/ublue-os/bluefin
image-version: stable

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
      - scope: user # Also add Flathub user repo, but no user packages

  - type: rpm-ostree
    repos:
      - https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
    optfix:
      - brave.com
    keys:
      - https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
    install:
      - brave-browser

  - type: bling
    install:
      - 1password

  - type: soar
    additional-repos: true
    auto-upgrade: true
    upgrade-interval: '3h'

  - type: chezmoi
    repository: "https://github.com/ekans/dotfiles"
    file-conflict-policy: replace

  - type: signing
