---
name: chauvenity-os
description: Personal image

base-image: ghcr.io/ublue-os/bluefin
image-version: stable

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - com.brave.Browser
      - scope: user # Also add Flathub user repo, but no user packages

  - type: signing
