---
name: chauvenity-os
description: Personal image

base-image: ghcr.io/ublue-os/bluefin
image-version: stable

modules:
  - type: files
    files:
      - source: system
        destination: /
  - type: signing
